server:
    port: 8080
    servlet:
        context-path: /round-2/api

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/round_2
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true